/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  denom: string;
}
export type ExecuteMsg = {
  publish_energy_transfer_offer: {
    charger_id: string;
    location: Location;
    name: string;
    plug_type: PlugType;
    tariff: number;
  };
} | {
  remove_energy_offer: {
    energy_offer_id: number;
  };
} | {
  start_energy_transfer: {
    driver: string;
    energy_to_transfer: number;
    energy_transfer_offer_id: number;
  };
} | {
  energy_transfer_started: {
    energy_transfer_id: number;
  };
} | {
  energy_transfer_completed: {
    energy_transfer_id: number;
    used_service_units: number;
  };
} | {
  cancel_energy_transfer: {
    energy_transfer_id: number;
  };
} | {
  remove_energy_transfer: {
    energy_transfer_id: number;
  };
};
export type PlugType = "type1" | "type2" | "c_h_ade_m_o" | "c_c_s" | "unspecified";
export interface Location {
  latitude: string;
  longitude: string;
}
export type QueryMsg = {
  denom: {};
} | {
  energy_transfer_offer: {
    id: number;
  };
} | {
  all_energy_transfer_offers: {};
} | {
  energy_transfer: {
    id: number;
  };
} | {
  all_energy_transfers: {};
} | {
  energy_transfer_offers: {
    owner: string;
  };
} | {
  own_energy_transfers: {
    driver: string;
    transfer_status: TransferStatus;
  };
} | {
  energy_transfers: {
    owner: string;
  };
};
export type TransferStatus = "Requested" | "Ongoing" | "Paid" | "Cancelled" | "Unspecified";
export type MigrateMsg = string;
export type ChargerStatus = "Active" | "Busy" | "Inactive" | "Unspecified";
export interface AllEnergyTransferOffersResponse {
  energy_transfer_offers: EnergyTransferOffer[];
}
export interface EnergyTransferOffer {
  charger_id: string;
  charger_status: ChargerStatus;
  id: number;
  location: Location;
  name: string;
  owner: string;
  plug_type: PlugType;
  tariff: number;
}
export type Timestamp = Uint64;
export type Uint64 = string;
export interface AllEnergyTransfersResponse {
  energy_transfers: EnergyTransfer[];
}
export interface EnergyTransfer {
  charger_id: string;
  collateral: number;
  driver: string;
  energy_to_transfer: number;
  energy_transfer_offer_id: number;
  energy_transferred: number;
  id: number;
  offered_tariff: number;
  owner: string;
  paid_date: Timestamp;
  status: TransferStatus;
}
export interface DenomResponse {
  denom: string;
}
export interface EnergyTransferResponse {
  energy_transfer: EnergyTransfer;
}
export interface EnergyTransferOfferResponse {
  energy_transfer_offer: EnergyTransferOffer;
}
export interface EnergyTransferOffersByOwnerResponse {
  energy_transfer_offers: EnergyTransferOffer[];
}
export interface EnergyTransfersByOwnerResponse {
  energy_transfers: EnergyTransfer[];
}
export interface OwnEnergyTransfersResponse {
  energy_transfers: EnergyTransfer[];
}